export const CREATE_NEW_TASK = "CREATE_NEW_TASK";
export const ADD_NEW_TASK = "ADD_NEW_TASK";
export const DELETE_TASK = "DELETE_TASK";

export const FETCH_TASK = "FETCH_TASK";
export const FETCH_TASK_SUCCESS = "FETCH_TASK_SUCCESS";
export const FETCH_TASK_ERROR = "FETCH_TASK_ERROR";

export const SEND_TASK = "SEND_TASK";
export const SEND_TASK_SUCCESS = "SEND_TASK_SUCCESS";
export const SEND_TASK_ERROR = "SEND_TASK_ERROR";

export const SEND_DELETE_TASK_SUCCESS = "SEND_DELETE_TASK_SUCCESS";
export const SEND_DELETE_TASK_ERROR = "SEND_DELETE_TASK_ERROR";